/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-File-Information.h
 #	source generated by 4D Plugin Wizard
 #	Project : File Information
 #	author : miyako
 #	2019/12/13
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_FILE_INFORMATION_H
#define PLUGIN_FILE_INFORMATION_H

#include "4DPluginAPI.h"

#include "ARRAY_TEXT.h"
#include "C_TEXT.h"
#include "C_LONGINT.h"

#if VERSIONWIN
#include "Strsafe.h"
#endif

#define ERR_CANT_QUERY_VALUE -1
#define ERR_CANT_GET_SIZE -2
#define ERR_CANT_GET_INFO -3
#define STRTEMP_SIZE 512
#define PARAMS_SIZE 10

#pragma mark -

void FILE_Get_information(PA_PluginParameters params);

#endif /* PLUGIN_FILE_INFORMATION_H */
